name: Build and Publish

on:
  push:
    branches:
      - master

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: v1.17
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -v ./src/tests -covermode=count
